name: Job on Main Only
on:
  push:
    branches:
      - main
      - dev
jobs:
  main-only:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository   
        uses: actions/checkout@v2

      - name: Print msg
        run: echo "This job running on the main branch"

  always-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository   
        uses: actions/checkout@v2

      - name: Print msg
        run: echo "This job runs on all branches"

      