name: Use Repo Secrets Workflow
on:
  workflow_dispatch:

jobs:
  secret-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print message 
        run: echo "Secrets key received"

      - name: Print secret length
        run: echo " secret length is ${#{{ secrets.MY_SECRET_KEY }}} "